services:
 web: 
    container_name: web
    build: .
    ports:
      - "3001:8080"
    environment:
        DB_HOST: postgres
    depends_on:
      - postgres
    networks:
      - common

networks:
  common:
    external: true

