services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "profile_sandbox"
    volumes:
        - "db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
        - common
  web: 
    container_name: web
    build: .
    ports:
      - "3001:8080"
    environment:
        DB_HOST: postgres
    depends_on:
      - postgres
    networks:
      - common

networks:
  common:
    external: true

volumes:
  db-data:
